install.packages("rvest")
install.packages("readxl")
install.packages("dplyr")
install.packages("data.table")
install.packages('Rcpp')
install.packages('stopwords')
install.packages('syuzhet')
install.packages('tidytext')
install.packages("tm")
install.packages("tidyverse")
install.packages("tidytext")
install.packages("glue")
install.packages("stringr")
install.packages("readxl")
install.packages("xlsx")
install.packages("ggplot2")
install.packages("viridis")
install.packages("hrbrthemes")
install.packages("reshape")
install.packages("gridExtra")
install.packages("magrittr")
install.packages("graphics")


library("rvest")
library("readxl")
library("dplyr")
library("data.table")
library("Rcpp")
library('stopwords')
library('syuzhet')
library('tidytext')
library('tm')
library('tidyverse')
library('tidytext')
library('glue')
library('stringr')
library('readxl')
library('xlsx')
library("ggplot2")
library("viridis")
library("hrbrthemes")
library("reshape")
library("gridExtra")
library("magrittr")
library("graphics")


source("links_scraping.R")
source("sentiment_analysis.R")
source("visualization.R")
source("other_analysis.R")

scraping()
analysis()
visualization()
other_visualization()